### ISSUE TITLE
Normalize document time stamps

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1000]
It's NoSQL, so it depends on the value you send to the DB.  Regardless of where the inconsistency is, the API (probably the `Document`) should simply enforce a normalisation.

_Originally posted by @maxkfranz in https://github.com/PathwayCommons/factoid/issues/997#issuecomment-892030677_

**Comment by jvwong** [comment]
I'm stumped on this one. 

Not sure how Date set in the model / browser can be interpreted correctly on server.

**Comment by maxkfranz** [comment]
Here's a search: https://github.com/PathwayCommons/factoid/search?q=lastEditedDate

It looks like it's always set as a `Date` type in the `Document` already.  So then, could it be that these problematic docs were generated from an older version of the code?  If that true and the code is fine now, then we just need to amend the problematic docs manually.

Another option is to change the code so it's always a string type.  We'd have to be consistent about the format used (probably just use ISO), but it would guarantee that there aren't any mismatches.  The downside with that option is that you can't do DB queries on the time anymore, since it's not a `Date` type.

**Comment by jvwong** [comment]
> It looks like it's always set as a `Date` type in the `Document` already. So then, could it be that these problematic docs were generated from an older version of the code? If that true and the code is fine now, then we just need to amend the problematic docs manually.
> 
> Another option is to change the code so it's always a string type. We'd have to be consistent about the format used (probably just use ISO), but it would guarantee that there aren't any mismatches. The downside with that option is that you can't do DB queries on the time anymore, since it's not a `Date` type.

This isn't an issue of old docs. Currently, at doc initialization, the server (nodeJS) sets `lastEditedDate` and its interpreted correctly as a rethinkdb `time` type. I think the problem is that, upon doc editing, a Date object in the browser gets inserted into  the `model/Document/Syncher` in the browser, and  the server / rethinkdb, interprets this as String. So my best guess is that `Date` needs to be set directly on the nodeJS server for rethinkdb to correctly interpret it as a `time` object.   

I guess we can just enforce a string and remember to use my little hack:

https://github.com/PathwayCommons/factoid/blob/065b82d184435c9060dadd1b4617d9ed1de645bd/src/server/routes/api/document/update.js#L91-L94

**Comment by maxkfranz** [comment]
It may be that it's not being serialised across the socket properly.  Dates aren't proper JSON values; they're JS objects (from classes).

Another simple option would be to use a number as the time value (i.e. Unix epoch).  That would be `unixEpoch = dateObject.getTime() / 1000` in JS.  Or you could use `dateObject.getTime()` directly, though the values will be much larger

Advantages:

- It will always serialise across the wire properly, because numbers are JSON serialisable.
- You can do DB queries on the number time, e.g. `date > x`.  This may be important in future if we want this to be semiautomated and performant.
- It's a bit simpler than strings, since you don't need to worry about which string format is being used.  Unix epoch is pretty standard.

Disadvantages:

- You still have to convert to JS `Date` objects if you want to do formatting etc.  Same downside as the stringified approach.
