### ISSUE TITLE
Alpha version Q1 2018

### ISSUE THREAD

**Issue by cccsander** [PathwayCommons/factoid#159]
Chris

**Comment by sacdallago** [comment]
I think this is the best place to have this discussion since the issue already exists and only needed a bit of a brush-up.

After today's call with @cccsander @d2fong @gbader , here is a MVP mockup from Sanderlab:
[chirs+chirs.pdf](https://github.com/PathwayCommons/factoid/files/1628048/chirs.chirs.pdf)

The idea is to give more context, as in #161 (see: status bar, enhancement in terms of NLP highlights, being discussed in #167) and partly re-drawing #160

There are now basically two three use cases:

1. User coming in with no text wanting to create a BioPax entry (the exact format being transparent to the user) via a graph AND form-based editor --> creates/edits --> submits
2. User coming in with text, applying NLP, getting a graph AND for-based representation of extracted text that may be edited (if not complete/correct) and then submitted
3. A user getting a link where she/he directly accesses the editing tool (number 2 in the PDF) with pre-filled NLP or no NLP and pre-populated graph/form, modify if needed and then submit [possibly the use case for journals]

I am aware that these use cases need to be expanded and explained, for now they are sort of a note-to-self :)

**Comment by sacdallago** [comment]
Was broken down in smaller issues
