### ISSUE TITLE
Tell users that the text is being processed

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#162]
When submitting a job (aka. text to be interpreted as a fact) there is no "loading wheel" --> The general feeling is: what's going on? Did I actually submit something or not?

**Comment by gbader** [comment]
It sounds like this is referring to the test harness page.  That is just for testing.  The idea is that factoid will be pre-populated with text mining results before the author user accesses the page. We are waiting to build all of that functionality until we speak to journals, because we've found in the past that each journal has a unique system and it will need to be customized for the pilot project.

**Comment by sacdallago** [comment]
Sounds reasonable and I understand the idea, nevertheless even for testing purposes (or demo purposes, or for the purpose of making this available as-is for the _"community oriented"_ use case) this is something fairly small that IMO needs to be addressed to avoid confusion/having users click multiple times/giving a talk and being unsure oneself if clicking actually _did something_
