### ISSUE TITLE
Reach text highlighting

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#167]
- Re-engineer current text input ( here: http://factoid.baderlab.org/new-document/fill )
- Get answer from reach
- Highlight text in text input with Reach annotations

**Comment by d2fong** [comment]
- highlight gene names that are recognized by reach
- highlight interactions and their types recognized by reach with a different colour

**Comment by d2fong** [comment]
https://github.com/PathwayCommons/factoid/commit/b8c5dcc02dd82fa6d6de69623b7bde1fa52ac4e5

**Comment by sacdallago** [comment]
Update: this goes back to https://github.com/PathwayCommons/factoid/issues/182#issuecomment-369708008

**Comment by metincansiper** [comment]
I have a few questions and thoughts considering this issue:

>Highlight text in text input with Reach annotations

Does this mean just highlighting specific parts of text while it is still editable? I mean will users still be able to edit the text when specific parts of it are highlighted? If it must still be editable I think it would bring some concerns to consider in terms of functionality and implementation. If that is the case I can explain these concerns. If not I think there could be a button of checkbox to toggle the availability of highlights. The text would become editable when the highlights are off and it would become non-editable when highlights are on.

I think that reusing ```highlighter``` component for this feature would be nice but it will require updating ```highlighter``` since this issue requires using different colors for highlighting references to  entities and interactions while ```highlighter``` does not support different colors (according to answer of my first question ```highligter``` would even need to be updated more).

Currently highlighter gets a list of terms to be highlighted (e.g. ```['term1', 'term2']```). To support this feature it would need to get different lists for different groups like the following:

```js
[
   { // entities
      list: ['ent1', 'ent2',...],
      class: ['highlighted-entity']
   },
   { // interactions
      list: ['int1', 'int2',...],
      class: ['highlighted-interaction']
   },
   ...
]
```
In this case, for example, the ```span``` that represents an entity of the text would have class ```highlighted-entity``` instead of ```highlighter-term``` and users can adjust style for different groups in that way.

Does this make sense or what would be an alternative way?

Also, should the entities or the interactions be prioritized? I mean for example an entity name would be ```abc``` and an interaction name would be ```abc interacts xyz```, in that case highlighter could highlight either ```abc``` or ```abc interacts xyz``` when ```abc interacts xyz``` is encountered. 

I am not sure if interaction names are supposed to be in that way but if so it would make more sense to prioritize interaction names. In current implementation the term which comes before in the terms list is prioritized. Therefore, this could be handled by adjusting the input for the terms accordingly. Maybe it is not expected but I can handle determining the "highlight style" when there is a name that is available for both an interaction and an entity in a similar way.

**Comment by sacdallago** [comment]
> Does this mean just highlighting specific parts of text while it is still editable? I mean will users still be able to edit the text when specific parts of it are highlighted? If it must still be editable I think it would bring some concerns to consider in terms of functionality and implementation. If that is the case I can explain these concerns. If not I think there could be a button of checkbox to toggle the availability of highlights. The text would become editable when the highlights are off and it would become non-editable when highlights are on.

For now, non-editable.

> I think that reusing highlighter component for this feature would be nice but it will require updating highlighter since this issue requires using different colors for highlighting references to entities and interactions while highlighter does not support different colors (according to answer of my first question highligter would even need to be updated more).

sounds good to me

> Also, should the entities or the interactions be prioritized? I mean for example an entity name would be abc and an interaction name would be abc interacts xyz, in that case highlighter could highlight either abc or abc interacts xyz when abc interacts xyz is encountered.

I would argue that the highlight has a degree of transparency (possibly, very transparent), so that overlaying two highlights would result in a darker colour (being a mixture of the two colours of the different entities (interaction + node) being highlighted). I think in the future it would rather be, that the entities are highlighted on hover, which will trigger only the relevant highlight without loading the text with all highlights at all time. But for now, that could be our initial goal (display all highlights in a non-editable text and overlay highlights for interactions and nodes).

**Comment by metincansiper** [comment]
Now I think that my initial approach was not appropriate because Reach results already include the exact start and end indices of entities and interactions. This means that we do not need to search for these terms in the text (This is what current highlighter component does and so reusing highlighter here would not make sense. We can introduce a new component that highlights the terms between given indices of text instead). 

In that case we will not need to care about whether a word is a part of an interaction or an entity since it is exactly defined by Reach output. This will also prevent mistakenly highlighting a word. I suppose in that case we will not need to use mixture of colors as well.

What do you think?

**Comment by metincansiper** [comment]
Sorry mixture of colors would still be needed since the exact substring that represent an interaction would include the exact substrings that represent entities.

**Comment by maxkfranz** [comment]
You can highlight entities and underline interactions for now.  A user will not understand different concepts if they are displayed the same way.  And as you noted, there is always overlap.

**Comment by metincansiper** [comment]
Okay, if mixing colors is preferred in the future it can easily be converted in this way (https://codepen.io/anon/pen/akggar?editors=1100)

**Comment by sacdallago** [comment]
Thanks @metincansiper and @maxkfranz, a very good idea with the underlying and highlighting, I assume it's much more effective graphically than overlapping highlights.

@metincansiper would be nice if for the call tomorrow you'd have a 1 minute example running that we can screen share :)

**Comment by metincansiper** [comment]
>@metincansiper would be nice if for the call tomorrow you'd have a 1 minute (or less) example running that we can screen share :)

Yes, sure.

**Comment by sacdallago** [comment]
@metincansiper sorry, I thought in the call yesterday we could make a statement about the current process, but it seemed more of a "we are all on the same page" situation :) We'll keep this for the next call in two weeks, and I'll bring it up offline to Chris
