### ISSUE TITLE
Add support for protein family grounding

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#180]
Add an entity grounding service that supports protein families and uses PFAM IDs.

Ref https://github.com/PathwayCommons/factoid/issues/168#issuecomment-363438094

**Comment by jvwong** [comment]
Paper mentioned in talk with Ben Gyori and John Bachman (Sorger):

[Bioentities: a resource for entity recognition and relationship resolution in biomedical text mining](https://www.biorxiv.org/content/early/2017/11/27/225698)

>In a task involving automated reading of ∼215,000 articles using the REACH event extraction software we found that grounding was disproportionately inaccurate for multi-protein families (e.g., “AKT”) and named complexes that involve multiple molecular entities (e.g. “NF-κB”)...

**Comment by jvwong** [comment]
A little bit of background is in order [see 'Support for protein families' for full detail](https://docs.google.com/document/d/1vh3WXiypZdowzaWFjd012oquhBThiRYnTrvxzEQugps/edit#).

# Challenges/requirements 

1. REACH can return grounding from [PFAM](https://pfam.xfam.org/) for an entity that references a protein family rather than a particular member  
  - Recognize protein family entities grounded via REACH
2. Biologists are often only aware of a family or complex, rather than individual members  
  - Allow a user to select a protein family for grounding  
3. A multitude of lexical synonyms are used to reference protein families and complexes  
  - Map commonly used names for family and complexes  

Let's narrow in on 1. and 2. for now.

# Case study

## The Ras signaling pathway

The following is a pathway figure taken from [Ward et al, Blood J, 2012](http://www.bloodjournal.org/content/120/17/3397?sso-checked=true). In this case, 'Ras', 'Raf' and 'PI3K' are references to protein families. 

![image](https://user-images.githubusercontent.com/4706307/37537155-0e02c1fc-2923-11e8-8893-e363f2105877.png)
> Figure 1 
The Ras switch. Ras phosphorylates Raf, leading to proliferation.

## The REACH response

Let's see what comes back from 'Ras phosphorylates Raf, leading to proliferation'.

![image](https://user-images.githubusercontent.com/4706307/37537451-0285ea24-2924-11e8-9bdc-ce606a3cc4c4.png)

```js
{
	"events": 
...
	"entities": {
		"frames": [

                            {
				"text": "Ras",
				"frame-id": "ment-api138-UAZ-r1-Reach-0-10304",
				"type": "family",
				"frame-type": "entity-mention",
				"end-pos": {
					"reference": "pass-api138-UAZ-r1-Reach",
					"offset": 3,
					"object-type": "relative-pos"
				},
				"xrefs": [
					{
						"namespace": "pfam",
						"species": "human",
						"object-type": "db-reference",
						"id": "PF00071"
					}
				],
				"object-type": "frame",
				"start-pos": {
					"reference": "pass-api138-UAZ-r1-Reach",
					"offset": 0,
					"object-type": "relative-pos"
				},
				"sentence": "sent-api138-UAZ-r1-Reach-0"
			},
…
}
```

So REACH maps 'Ras' to a PFAM database accession PF00071.


## The PFAM entry for the Ras family 

PFAM refers to families via an 'accession' (e.g. PF00071) and an ID (e.g. 'Ras'). They provide a [RESTful interface]( http://pfam.xfam.org/help#tabview=tab11 ) for retrieving xml given any entry (an 'entry' in PFAM is an ID or an accession). For example, we can POST to 'http://pfam.xfam.org/family/' with the form parameters 'output=xml' and 'entry=PF00071':

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- information on Pfam-A family PF00071 (Ras), generated: 15:32:48 16-Mar-2018 -->
<pfam
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="https://pfam.xfam.org/"
      xsi:schemaLocation="https://pfam.xfam.org/
                          https://pfam.xfam.org/static/documents/schemas/pfam_family.xsd"
      release="31.0"
      release_date="2017-03-01">
	<entry entry_type="Pfam-A" accession="PF00071" id="Ras">
		<description>
			<![CDATA[
Ras family
]]>
		</description>
		<comment>
			<![CDATA[
Includes sub-families Ras, Rab, Rac, Ral, Ran, Rap Ypt1 and more. Shares P-loop motif with GTP_EFTU, arf and myosin_head.  See Pfam:PF00009 Pfam:PF00025, Pfam:PF00063. As regards Rab GTPases, these are important regulators of vesicle formation, motility and fusion. They share a fold in common with all Ras GTPases: this is a six-stranded beta-sheet surrounded by five alpha-helices [1].
]]>
		</comment>
		<clan_membership clan_acc="CL0023" clan_id="P-loop_NTPase" />
		<go_terms>
			<category name="function">
				<term go_id="GO:0005525">GTP binding</term>
			</category>
			<category name="process">
				<term go_id="GO:0007264">small GTPase mediated signal transduction</term>
			</category>
		</go_terms>
		<curation_details>
			<status>CHANGED</status>
			<seed_source>Swissprot</seed_source>
			<previous_id>ras; </previous_id>
			<num_archs>769</num_archs>
			<num_seqs>
				<seed>60</seed>
				<full>44451</full>
			</num_seqs>
			<num_species>1032</num_species>
			<num_structures>1044</num_structures>
			<percentage_identity>29</percentage_identity>
			<av_length>152.20</av_length>
			<av_coverage>59.73</av_coverage>
			<type>Domain</type>
		</curation_details>
		<hmm_details hmmer_version="3.1b2" model_version="21" model_length="162">
			<build_commands>hmmbuild  -o /dev/null HMM SEED</build_commands>
			<search_commands>hmmsearch -Z 26740544 -E 1000 --cpu 4 HMM pfamseq</search_commands>
			<cutoffs>
				<gathering>
					<sequence>21.6</sequence>
					<domain>21.6</domain>
				</gathering>
				<trusted>
					<sequence>21.6</sequence>
					<domain>21.6</domain>
				</trusted>
				<noise>
					<sequence>21.5</sequence>
					<domain>21.5</domain>
				</noise>
			</cutoffs>
		</hmm_details>
	</entry>
</pfam>

```

They also have a nice landing page for most family members:

![image](https://user-images.githubusercontent.com/4706307/37537923-7234ba5c-2925-11e8-9076-74e718a98b2a.png)

**Comment by jvwong** [comment]
## Idea: How might we search for a protein family?

From my understanding, a. PFAM is primarily based on UniProtKB proteomes and b. UniProt supplies PFAM information under ‘Family and Domains’ for any entry, when available.

Consider a [UniProt search for Ras (human)](http://www.uniprot.org/uniprot/?query=ras&fil=organism%3A%22Homo+sapiens+%28Human%29+%5B9606%5D%22&sort=score). Note the 'Protein families' column available.

![image](https://user-images.githubusercontent.com/4706307/37538290-9498cfc4-2926-11e8-9334-973cbb720cbf.png).

If we look at the first entry [RASK_HUMAN](http://www.uniprot.org/uniprot/P01116), and scroll down to the 'Family and Domains' section, there's an entry for PFAM:

![image](https://user-images.githubusercontent.com/4706307/37538590-74477e86-2927-11e8-9292-48ea874a0e66.png)

This effectively recapitulates the PFAM keyword search. I didn't see a RESTful endpoint for querying on PFAM.

**Comment by jvwong** [comment]
## How do we present protein family options to users?

Let's grab the family/families that come for free with any given UniProt record. 

One caveat is that proteins can belong to 0, 1, or more families and it is not always clear which one to select. For example, search UniProt for ‘Phosphoinositide 3-kinase’. In this case 4 families come back for 'PK3CG_HUMAN'.

**Comment by maxkfranz** [comment]
Edit (Max): Removed link to Google Doc.  We can't have just anyone editing it from a public link on Github.  Sharing links by email is fine.

**Comment by maxkfranz** [comment]
Trying to do cross-references with many Uniprot queries would be a mess.  I don't think they have a family lookup service or a family search service.

[EBI search](https://www.ebi.ac.uk/ebisearch/overview.ebi/about) has [webservice](https://www.ebi.ac.uk/ebisearch/swagger.ebi) support.

- Allows for lookups for multiple entity types, [e.g. 'ras'](https://www.ebi.ac.uk/ebisearch/search.ebi?db=allebi&query=name:(ras)).
- Allows type-specific queries, [e.g. 'ras' protein family](https://www.ebi.ac.uk/ebisearch/search.ebi?db=proteinFamilies&query=name:(ras)).  For protein family queries, InterPro is the source, [e.g 'ras'](https://www.ebi.ac.uk/interpro/search?q=ras%20type:family).
- Gives XML output, [e.g. ras xml](https://www.ebi.ac.uk/Tools/dbfetch/dbfetch?db=interpro&id=IPR001806&format=interproxml&style=raw), [e.g. ras UI](http://www.ebi.ac.uk/interpro/entry/IPR001806).

Pfam REST: 
- [Docs](http://pfam.xfam.org/help#tabview=tab11)
- No by-name search in API.  Only sequence searching is allowed.
- It's possible to just get and cache all the families: See 'Pfam-A family list' /families?output=xml
- You can do cross-reference lookups, e.g. Interpro => Pfam

The most important usecase is search, so the EBI webservice looks better than Pfam.  We may consider just cross-referencing with Pfam IDs but not using Pfam webservices -- or only when necessary.

More investigation is necessary, but this gives us something to start with re. services.

**Comment by jvwong** [comment]
Nice catch, I didn't see a keyword search service on InterPro so this EBI search looks like it fits the bill.
