### ISSUE TITLE
Add 'name': User-specified text description  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#211]
## Description of new feature

Allow a user to enter and update a pathway title or name.   

## Motivation for new feature

Data entered into Factoid will probably not be best described by the manuscript title. 
Our PC search app uses the 'name' index field to format queries.  

Possibly related to #200, 'seed page'.

**Comment by sacdallago** [comment]
I would argue that this could be rather in the later stages, like editing or saving, rather than in the "seed page". Rationale: if a user gets the link to the factoid extracted from their paper, they would have to go back to change the name? Or they could change the name in three different places, which might be a bit "too much", e.g. unnecessary.

I would keep it either at the level of "put this factoid into PC" or when editing

**Comment by maxkfranz** [comment]
N.b. model already has support for this
