### ISSUE TITLE
Deleting an interaction

### ISSUE THREAD

**Issue by fdurupinar** [PathwayCommons/factoid#247]
## Interaction delete bug

Clicking on the delete button of an interaction row always removes the last interaction. But the interaction content looks correct when the page is reloaded.

**Comment by d2fong** [comment]
I think it is because you have to force the component to update.  You could try subclassing the dirty component: https://github.com/PathwayCommons/factoid/blob/master/src/client/components/dirty-component.js#L22

Anytime you delete an interaction, you can call the dirty method.

**Comment by fdurupinar** [comment]
Using dirty component did not help either. 

Relevant pieces of code are:

https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/index.js#L203-L207

https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/index.js#L140-L164

**Comment by maxkfranz** [comment]
Also assigning to self as a reminder to give feedback on the code to look for gotchas

**Comment by metincansiper** [comment]
While debugging I tried to print out id of interactions in different code segments. I figured out that after deletion the correct interaction ids are printed out [here](https://github.com/PathwayCommons/factoid/blob/form-templates/src/client/components/form-editor/index.js#L205). However, the ones printed out [here](https://github.com/PathwayCommons/factoid/blob/form-templates/src/client/components/form-editor/protein-modification-form.js#L11) are not correct. Then I realized that the reason for that was the constructor of ```InteractionForm``` is called only at the beginning. After searching for the reason of that I run into [a stackoverflow question](https://stackoverflow.com/questions/29074690/react-why-components-constructor-is-called-only-once) where one of the answers explains the reason and a possible solution. 

The reason is [reconciliation](https://reactjs.org/docs/reconciliation.html) that react uses for improving performance. I think that react thinks that we are rendering the same components and so it is rendering the previous n-1 components when we delete one of the n components. 

I tried the solution that is proposed in the stackoverflow answer about using a unique key prop. I mean in [this](https://github.com/PathwayCommons/factoid/blob/form-templates/src/client/components/form-editor/index.js#L207) line I changed ```{ document:doc, interaction:interaction, description: form.type}``` as ```{ key: interaction.id(), document:doc, interaction:interaction, description: form.type}```. After doing that it works fine. I will make a PR after making sure that this solution has no side effect and it is the best practice.

**Comment by maxkfranz** [comment]
If that's the case, take a look at the EntityInfo component: https://github.com/PathwayCommons/factoid/blob/master/src/client/components/element-info/entity-info.js#L121

It uses a `data` object in place of the `state` -- though it just calls `setState()` to hint to React to render.

@metincansiper Maybe you could create a `DataComponent` that uses a pattern like this?  You could make `DataComponent` a subclass of `DirtyComponent`, similar to how @d2fong suggested.  That would make it cleaner than the approach used in `EntityInfo` component -- and the `EntityInfo` component could eventually be refactored to also subclass `DataComponent`.

**Comment by fdurupinar** [comment]
@metincansiper,  issue #248 is probably related to the same problem.

**Comment by maxkfranz** [comment]
@fdurupinar You need to `synch()` only once after creation of an object to turn on synching for that object:

https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/index.js#L150

**Comment by maxkfranz** [comment]
So this synch() is enough for entities: 

https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/index.js#L97

**Comment by maxkfranz** [comment]
But there should also probably be a synch() for interactions here: 

https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/index.js#L105
