### ISSUE TITLE
Synchronizing entity info with grounding popover

### ISSUE THREAD

**Issue by fdurupinar** [PathwayCommons/factoid#248]
## Current (buggy) behaviour
When an entity name is updated in the form, its popover does not reflect this change. E.g.
The entity name is initially correctly selected as RAF (1), but it cannot be updated to AKT1 (1).

1. 

 ![screen shot 2018-04-10 at 3 01 36 pm](https://user-images.githubusercontent.com/13474166/38585847-420e15d0-3cd0-11e8-81f2-df76c0a09aa7.png)

2.

 ![screen shot 2018-04-10 at 3 01 53 pm](https://user-images.githubusercontent.com/13474166/38585854-43e982b8-3cd0-11e8-9c04-b8f930328f18.png)

## Minimum steps to reproduce
In the form UI:

- Writea gene name in an entity box and click on the box to see its grounding popover.
- Press esc and update the entity name.
- Click on the entity box again to see that entity name is not updated.

## Relevant code
https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/entity-form.js#L68-L76

**Comment by maxkfranz** [comment]
Assigning to self just as a reminder to provide pointers re. the code tomorrow

**Comment by fdurupinar** [comment]
Same solution as #247. We need to add a unique identifier, in this case entity name, to guarantee rendering update.  
https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/entity-form.js#L74

**Comment by maxkfranz** [comment]
@fdurupinar @d2fong @metincansiper Do the keys just cause a force re-init of a component, or is it sophisticated enough to maintain existing components with the same key?  If it just forces a re-init every time, then you lose all the `data` and/or `state`, which is problematic for a stateful component.

We have a OO model, which is useful for manipulating the model effectively for Factoid.  That doesn't always make an easy fit with a lot of the React examples out there.  

What I've done in the Editor component is to just use the model directly.  There are listeners set up in the constructor (or in componentDidMount for Cytoscape.js-related things) that cause the Editor component to update and rerender.  Instead of subcomponents for the Editor, I've used simple functions to factor out separate rendering concerns.  Here's an example for the buttons: https://github.com/PathwayCommons/factoid/blob/master/src/client/components/editor/buttons.js

You can see that the function gets a reference to the component (controller) so that controller methods on the component are accessible in the button render function.  That way, you have access to all of the view objects and the model objects of the controller without having to worry about reconciliation issues or keys.  It also sidesteps issues like [having to do forceUpdates across components](https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/entity-form.js#L35).

Maybe this approach would be useful in the form editor.

**Comment by fdurupinar** [comment]
@maxkfranz, @metincansiper It does not maintain existing components, it recalls the constructor every time. Although this is not a problem for the current state of the form editor as each input box takes its data directly from the model, it is potentially problematic.

**Comment by metincansiper** [comment]
@fdurupinar @maxkfranz @d2fong I think React infers if a component should be updated. However sometimes it would make wrong decisions that would cause inefficiencies or wrong rendering issues just like this case. 

From my understanding ```keys``` help React to decide a component should be updated. If the ```keys``` are same it decides that it is the  same component and does not update it. Otherwise , it updates it. 

Therefore, I think that we cannot say that ```keys``` just force re-init of a component, it would prevent re-init of a component as well.

**Comment by fdurupinar** [comment]
In this specific case, although we achieve the desired result, using name as a key is not the best solution. 

Here, EntityInfo is updated even when "name" is not passed as a key, but Popover is not:
https://github.com/PathwayCommons/factoid/blob/4bddc5b0838c24ef44f28671320b40484d12cfb7/src/client/components/form-editor/entity-form.js#L68

**Comment by metincansiper** [comment]
@fdurupinar if I understand correctly this is related to what I mean by possible side effect in [this comment](https://github.com/PathwayCommons/factoid/issues/247#issuecomment-380295608). However, actually maybe it should not be called a side effect. 

In this case if ```name``` is not the only thing that effect rendering I think it would not be enough to represent the key by itself. I think that if keys concept is to be used here then a key that covers all the properties that effect rendering would need to be generated by a hash function.

For the case in #247 interaction ```id``` would be enough for identifying a component but even if it is the same component it would still need to be re-created when the fields of it are updated. Therefore, a similar hash function would be needed there as well if the keys concept will be used (But I am not sure about it, maybe id would be enough itself for #247 ).

**Comment by maxkfranz** [comment]
All entities and interactions have UUIDs for IDs.  If you need a unique key, you should use the `el.id()`.

**Comment by fdurupinar** [comment]
I wasn't clear in my first comment. Id does not trigger react rendering in this case because it is not updated wrt text. That's why I used el.name() to make sure react updates the rendering.

**Comment by metincansiper** [comment]
That was the reason why I proposed to at least considering creating keys by a hash function.

**Comment by metincansiper** [comment]
@fdurupinar  Okay then I misread this comment of you ```Here, EntityInfo is updated even when "name" is not passed as a key, but Popover is not```  and supposed that something is not updated properly even after using a key and so thought that name is not the only thing that affects rendering. You can ignore my previous comments.

**Comment by metincansiper** [comment]
But I can say that this other comment of you "Id does not trigger react rendering in this case because it is not updated wrt text" seems to be related to my concern. Since id will still be the same for the component React thinks that there is nothing to be updated and will not re-create the component. However, actually the name changes and so it should be updated. If there was another thing that affects rendering besides the name then we would need to use a hash function here to generate the key. That was what I mean.

**Comment by maxkfranz** [comment]
If any update to the subcomponents makes you think 'now I have to update the key in the above component', then it's probably better to use the pattern I suggested where keys are not necessary -- like the button example in the Editor.

**Comment by metincansiper** [comment]
@maxkfranz agree that using keys for subcomponents is hard to maintain in this case, so would not be preferable. 

However, I could not understand how to apply the pattern that you suggested to this problem. The main problem here is that a subcomponent (```EntityInfo```) is not re-created when the name is updated because of reconculation issues. I was thinking that the way of solving this is either using unique keys for elements (I think it will not be used for this issue) or using ```shouldComponentUpdate()``` by means of ```DirtyComponent``` or in an other way as discussed in #247 and #249. 

I think even in your proposed solution there are still subcomponents (I mean like tooltips in ```button.js```). You mentioned that in your example events causes editor to update and re-render. The only event that is emitted by ```buttons.js``` is ```opentip```. Which code segment or function makes editor updating itself on ```opentip``` event (I think it is listened to [here](https://github.com/PathwayCommons/factoid/blob/master/src/client/components/editor/cy/tippy.js#L35))? And would this approach be enough to update ```EntityInfo``` components themselves by eleminating reconculation issues?

Sorry about that if I am missing an easy point?

**Comment by maxkfranz** [comment]
The components have been updated such that they each automatically use an appropriate key.  Please use this pattern in future.

https://github.com/PathwayCommons/factoid/blob/543d9488fa029aac731817761ddfd5bdfab93c47/src/client/components/notification/base.js#L57

**Comment by fdurupinar** [comment]
@maxkfranz Is there an example about how to use these components, particularly PopoverNotification ? E.g. what is the notification field?

**Comment by maxkfranz** [comment]
> E.g. what is the notification field?

A `Notification` VO, in the same dir as the rest of the notification stuff.
