### ISSUE TITLE
Replace an interaction participant

### ISSUE THREAD

**Issue by fdurupinar** [PathwayCommons/factoid#250]
## Description of new feature
A method for replacing the participant of an interaction with another without changing the order of elements in the array.

## Motivation for new feature
In the form UI, when two entities are merged into one based on grounding info, simply removing the old one and adding the new one do not work as desired, as the new participant is added to the end.  The order of entities of an interaction is important because input boxes are filled with the corresponding entities.

I.e. the line:
https://github.com/PathwayCommons/factoid/blob/46b5dee10a7bc3ddd94daeb2cae54830866f2735/src/client/components/form-editor/entity-form.js#L85

should be rewritten as:
 intn.replaceParticipant(entity, mergedEntity);

**Comment by fdurupinar** [comment]
@maxkfranz,  @d2fong, your help is appreciated as the implementation possibly requires updating the ElemenSet and Syncher classes.

**Comment by metincansiper** [comment]
@maxkfranz In todays call you mentioned that this would not be straightforward because entities are stored in an unordered way. 

I looked for this issue yesterday and what I found out was that elements are stored in an unordered set in ```ElementSet``` class but we have them [ordered](https://github.com/PathwayCommons/factoid/blob/master/src/model/syncher.js#L554) in ```Syhncer``` class. And ```element()``` method of ```ElementSet``` [reads ordered entries from ```Syhncer```](https://github.com/PathwayCommons/factoid/blob/master/src/model/element-set.js#L187). 

Can we implement a replace method relying on that entries are ordered in ```Syhncer``` and ```element()``` method eventually reads entries from there?
