### ISSUE TITLE
App bar redesign

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#289]
## Description of new feature

- an app bar for the network and form editors

## Motivation for new feature

- allow users to go to the new factoid page
- allow users to switch between the different editors
- allow users to export the factoid doc to biopax
- allow users to rename the doc

**Comment by d2fong** [comment]
@maxkfranz Did you make any progress on this?  I can start working on it if you are busy.

**Comment by maxkfranz** [comment]
@d2fong I've pushed a branch called bar-redesign.  I rebased it before pushing it, so it should have the latest stuff from the unstable branch.  So far, it has the most important part -- the buttons for my factoids etc.

Things to consider

- The renamer component isn't there yet.  Maybe this should be put in the document creation wizard instead, since a user would only ever name the document once.  In most cases, the user would not have to enter the title manually:  It would be prepopulated for them already by the time they receive the edit linkout emails.
- The help, more-menu, and link buttons are different from everything else in the toolbar.  Those buttons don't modify the graph.  We should consider eventually moving them to the right-hand side of the screen, along with potentially the task list when it's merged in.  We should probably leave this until everything is merged in together and use the left side for now.

**Comment by d2fong** [comment]
![screen shot 2018-05-31 at 3 29 55 pm](https://user-images.githubusercontent.com/2328291/40803813-8a70d36e-64e7-11e8-9eed-afc2232b2f30.png)

Ported the more tools button to the form editor

**Comment by maxkfranz** [comment]
I think we can close this, as we've addressed most everything in the "..." menu.

I'll create separate tickets for the remaining tweaks:

- Add document renamer to the document creation wizard
- Add Factoid logo to RHS toolbar
- Put save and linkout buttons in the "..." menu
