### ISSUE TITLE
Re-evaluate interaction type list

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#297]
## Description of new feature

Consider

- Renaming existing interaction types
- Adding new interaction types

## Motivation for new feature

- Ensure a certain level of BioPAX coverage
- Make sure that the names are unambiguous

**Comment by maxkfranz** [comment]
TODO reserving comment for listing current type mappings

**Comment by maxkfranz** [comment]
@jvwong I've filled in the above list.  Let me know if you notice that I've overlooked something, or feel free to edit the text directly.

**Comment by jvwong** [comment]
Just some minor edits. I think based on the last call we'd have to explicitly declare some types in the UI using more tailored language. In particular, 

- Explicitly state  'Binding'
- Cases where 'Chemical' is involved

**Comment by metincansiper** [comment]
I looked at the table here to see if I did everything correctly in terms of biopax export. It seems that I would need to update something for general interaction type since currently I am always creating molecular interaction for it.

Also for modification type I was only covering the case where the both sides are proteins and seems like current factoid code only allows proteins (https://github.com/PathwayCommons/factoid/blob/unstable/src/model/element/interaction-type/modification.js#L23). However, in the table C -> P  and C -| P are listed under modification. Will they be supported later?

@maxkfranz @jvwong 

- I could not fully understand what "SIF chemical-affects but no entity state info or superclass interaction" means. Should C -> P, C -| P be exported to the biopax in different way when interaction type is general (rather than protein chemical or modification)? 
- Super class interaction does not correspond to something from cPath2 Formats but it is directly the ``Interaction`` class from biopax level 3. Am I right?
- Looks like factoid enables adding general interaction between chemicals but C * C is classified as unsupported here. Should I just pass it when both participants of general interaction is chemicals?
- Is now a good time to make the changes that I mentioned above? Because this issue is still open and general modifications are always names as "A interacts with B" now independent of types of A and B.

**Comment by maxkfranz** [comment]
> I could not fully understand what "SIF chemical-affects but no entity state info or superclass interaction" means. Should C -> P, C -| P be exported to the biopax in different way when interaction type is general (rather than protein chemical or modification)?

It means it's ambiguous.  It could be chemical-affects (but you don't know how it affects protein state) or it could be the top-level interaction in biopax.  Probably the second is safer.

> Super class interaction does not correspond to something from cPath2 Formats but it is directly the Interaction class from biopax level 3. Am I right?

Yes

> Looks like factoid enables adding general interaction between chemicals but C * C is classified as unsupported here. Should I just pass it when both participants of general interaction is chemicals?

The subtypes aren't supported, but you could use a general interaction to represent it for now.

> Is now a good time to make the changes that I mentioned above? Because this issue is still open and general interactions are always described as "A interacts with B" now independent of types of A and B.

I don't think it's absolutely necessary.  It's not as important as fixing any bugs we may find, but it's at least as important as fixing design issues in the form.  So it makes sense to do it in a feature branch for now and we can evaluate merging it once complete.

**Comment by maxkfranz** [comment]
Proposed changes:

- 'General' => 'General (none of the below)'
- 'Expression' => 'Gene expression'
- 'Modification' => 'Protein modification'
  - Also allow C -> P and C -| P
- 'Protein-chemical' => 'Protein-chemical interaction'
  - Alternatively, remove this type altogether and always use generic.  The Biopax export can determine type based on direction and sign.

**Comment by maxkfranz** [comment]
Addressed by PR : UI tweaks and fixes #332
