### ISSUE TITLE
Form-graph synchronization

### ISSUE THREAD

**Issue by fdurupinar** [PathwayCommons/factoid#307]
## Environment info

Browser version (client) : Chrome 66.0.3359.181 (Official Build) (64-bit)
Node.js version (server) :v8.2.1

## Current (buggy) behaviour

When an interaction is added on the graph editor, it appears empty on the form-editor.

## Desired behaviour

The graph and form editors should work synchronously.

## Minimum steps to reproduce

This was fixed for a short time (7a391a9) but got broken again.

**Comment by fdurupinar** [comment]
@metincansiper 
> I think it is working just like 7a391a9.
However, when an interaction is added from network editor it seems like the following in form editor (the one where only the delete icon is visible is the one added from network editor. It was the same in 7a391a9):
screen shot 2018-06-07 at 11 39 46 am

That's not correct. I couldn't replicate the problem with 7a391a9.

**Comment by metincansiper** [comment]
@fdurupinar 
I still keep having the buggy behaviour for 7a391a9. I highly suspect that this would be related to installed software because when I tried to reproduce it from latest versions of form-components and unstable and remotely deployed unstable on different web browsers I got different results. 

For me it is only working fine for remotely deployed unstable and Chrome (Version 64.0.3282.140). The remotely deployed unstable does not work on my Safari (Version 11.1.1).

Would you try to reproduce the same error from form-components on your computer? I suppose it would be working for you since 7a391a9 works fine on your computer. Would you share your node and web browser versions?

**Comment by metincansiper** [comment]
I think that the reason of this bug is that when an interaction is added from the network editor its participant list comes empty on form-editor. 

I suppose that the problem would be more general than this. I mean that seems like the participant lists are empty on any other open network editor tabs as well. 

That would be the underlying problem of #313 so seems like this bug would be based on #313.

**Comment by d2fong** [comment]
@fdurupinar @metincansiper 
> When an interaction is added on the graph editor, it appears empty on the form-editor.

Do you mean added an incomplete interaction?  Or do you mean completing an interaction?

**Comment by metincansiper** [comment]
@d2fong 
I suppose it is about adding a complete interaction. However, it would be better if @fdurupinar confirms.

Let's just think about adding a complete interaction. For my case when I add a complete interaction from the network editor the following is what I see in the form editor (without refreshing the page):

<img width="518" alt="screen shot 2018-06-12 at 3 04 57 pm" src="https://user-images.githubusercontent.com/6534865/41319864-24d18c8c-6e52-11e8-9f24-14bbab5beb3d.png">

Does this work fine for you in form-fixes branch or do you get the same result with me?

According to what I understand from #313 something is working different in my computer.

**Comment by d2fong** [comment]
@metincansiper yes that is working fine for me too.

**Comment by d2fong** [comment]
Let me try using different versions of node

**Comment by d2fong** [comment]
Using node v8.2.1 I am unable to reproduce the issue described here or the issue described in #313

**Comment by d2fong** [comment]
When is the last time you restarted your computer?

**Comment by maxkfranz** [comment]
I’m able to reproduce both issues locally after playing around with things. I’ve been working on cleaning up the form code and it seems to improve things. I’ll update later today with my results.

**Comment by d2fong** [comment]
tips on how to reproduce it?

**Comment by maxkfranz** [comment]
I fiddled with

- node_modules
- nvm
- old doc vs new doc

Not sure what did it, but I can reproduce for a certain doc on my machine so I don't want to touch anything.

I have some changes that seem to resolve things, but they need some more testing and some cleanup before pushing.

@d2fong Could we review and test my changes in person tomorrow morning in the lab?

**Comment by d2fong** [comment]
Alright sounds good.
