### ISSUE TITLE
Make the styling more consistent throughout different pages of the app

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#338]
## Description of new feature

- [ ] Replace the green colour with the blue colour used throughout the rest of the app (PC colour scheme) to make things more consistent.
  - [ ] The "Try Factoid" button
  - [ ] The editor selection could use the blue colour for highlighting
- [ ] The links on the top of the landing page could use the default blue underline
- [ ] The logo could be beside the "Factoid" title for consistent branding

## Motivation for new feature

Consistency / polish

**Comment by sacdallago** [comment]
Personally, the title on top of the network editor feels a bit "thrown out there".  I can't think of a specific suggestion that would definitively improve this, but since it's non-editable, why not put it as a footnote? E.g. right-bottom corner.
Additionally, why is it non-editable in the first-place and where could a user edit the title _after_ having played around with a network?
