### ISSUE TITLE
Will users get that arrow terminus refers to the edge/event?

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#348]
Will users get that arrow terminus refers to the edge/event (rather than the node/entity)? In other words, will users interpret the graph as 'Activity Flow'-like, whereas Factoid does not? 

Concretely, consider the following passage:

> ATM can inhibit MDM2 via phosphorylation. 

Strictly speaking, this is the proper output:

![image](https://user-images.githubusercontent.com/4706307/41982490-8b3178f4-79f9-11e8-9a11-27c01f8cbbd2.png)

But I would have drawn the following Activity Flow-like representation, where the arrow terminus reflects the resulting 'activity' of the target entity MDM2 (which is irrelevant in 'SBGN-PD'/BioPAX):

![image](https://user-images.githubusercontent.com/4706307/41982631-eb483822-79f9-11e8-858d-3689971d90de.png).

From reviewing some of the previous user testing, I suspect many users will make the same 'mistake'. Indeed, even REACH output interprets the `controlled` argument to be an entity (MDM2):

```js 
{
	"events": {
		"frames": [
			{
				"frame-id": "evem-api524-UAZ-r1-Reach-0-3183",
				"text": "ATM can inhibit MDM2",
				"arguments": [
					{
						"text": "MDM2",
						"argument-type": "entity",
						"type": "controlled",
						"object-type": "argument",
						"index": 0,
						"arg": "ment-api524-UAZ-r1-Reach-0-13008"
					},
					{
						"text": "ATM",
						"argument-type": "entity",
						"type": "controller",
						"object-type": "argument",
						"index": 0,
						"arg": "ment-api524-UAZ-r1-Reach-0-13007"
					}
				],
				"type": "activation",
				"frame-type": "event-mention",
				"subtype": "negative-activation",
				"is-direct": false,
				"end-pos": {
					"reference": "pass-api524-UAZ-r1-Reach",
					"offset": 20,
					"object-type": "relative-pos"
				},
				"trigger": "inhibit",
				"object-type": "frame",
				"start-pos": {
					"reference": "pass-api524-UAZ-r1-Reach",
					"offset": 0,
					"object-type": "relative-pos"
				},
				"sentence": "sent-api524-UAZ-r1-Reach-0",
				"found-by": "Negative_activation_syntax_1_verb",
				"verbose-text": "ATM can inhibit MDM2 via phosphorylation."
			}
		],
		...
	},
	"entities": {
		"frames": [
			{
				"text": "ATM",
				"frame-id": "ment-api524-UAZ-r1-Reach-0-13007",
				"type": "protein",
				...
			},
			{
				"text": "MDM2",
				"frame-id": "ment-api524-UAZ-r1-Reach-0-13008",
				"type": "protein",
				...
			}
	...
}
``` 

see #252

**Comment by maxkfranz** [comment]
Ultimately, the problem is trying to represent two (related) interactions in one:

(A) ATM phosphorylates MDM2

(B) ATM inhibits MDM2 via (A)

**Comment by IgorRodchenkov** [comment]
In PD,
the object for "activate" and "inhibit" verbs should be a process (transcription, binding, etc..) and not a physical entity. Basically, a protein (any physical entity) is always active (having activity aka concentration and participating in some processes). A modified (phosphorylated) protein is not the same as its unmodified or modified in a different way state - chemical formulas are different.
ATM doesn't phosphorylate MDM2 (phosphate group does); it catalyses the reaction of MDM2 protein phosphorylation at a particular site. ATM does not inhibit MDM2: it's either the phosphorylated MDM2 (call it _inactive_, given the context) cannot participate in the next interaction, or it becomes inefficient (due to different equilibrium constants of that next process...).

2H2 + O2 = 2H2O
- does oxygen inhibit hydrogen or activates (in water)? :)

Correct me if I am wrong (or forgot things), are we still trying to mix ER,AF and PD and perhaps something else in Factoid? Looks, ER, AF cannot be easily converted to a BioPAX (the other way around seems possible).

**Comment by jvwong** [comment]
Made clear in discussions and model documentation that we do not conflate activation of process and participant.
