### ISSUE TITLE
Submission to BioPAX/SBGN: Missing types 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#401]
> Looks like no edge created for “protein activates protein” and “chemical activates protein” cases. 

[Here](http://unstable.factoid.baderlab.org/document/f799efdb-c81d-4049-a078-cbf525503e45/f3db2d94-b835-4ddb-9df3-064d1f7ae15b) is a factoid document created from http://unstable.factoid.baderlab.org. After submitting it to PC we have [this result](http://appsbeta.pathwaycommons.org/factoids/f799efdb-c81d-4049-a078-cbf525503e45) in http://appsbeta.pathwaycommons.org. 

See that the interaction between FSHB and IGF1 (protein activates protein) and the one between Estradiol and LEP (chemical activates protein) are missing in the resulting graph.

**Comment by IgorRodchenkov** [comment]
@jvwong  @metincansiper @maxkfranz 

The BioPAX looks just fine - as we designed and expected it. So, this must be either  the paxtools/sbgn-converter (java) issue or sbgnml-to-cytoscape npm module issue.

@metincansiper could help make sure the problem is not in sbgnml-to-cytoscape and fix there if it indeed is.

I could create an issue and try to test and fix if it is in Paxtools.

FYI: `http://web.newteditor.org/` and `http://www.cs.bilkent.edu.tr/~ivis/SBGNViz.js` both do much worse job than app-ui using the same input SBGN model.

**Comment by IgorRodchenkov** [comment]
I confirm that it's a Paxtools/sbgn-converter issue BioPAX/Paxtools#41

**Comment by IgorRodchenkov** [comment]
95% fixed :) tyr it...
I also noticed that in case of "BMP2 activates JUN via phosphorylation", you cannot see "inactive"/"active" states on the JUN, but can see "!phosphorylated" and "phosphorylated"...
