### ISSUE TITLE
Allow any 'sign' value for Binding interaction 'type' 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#454]
Background: As detailed in our Google Doc 'Factoid binary interaction types', each interaction 'type' (mechanism) is accompanied by a set of valid 'sign' attribute values. 

The suggestion here is to allow type=binding to have any 'sign' value: 'positive', 'negative' or 'unsigned'. 

This can be accomplished more generally by removing restrictions on 'sign' values given any 'type'. The caveats for this general approach include determining source/target for  type='Transcription/translation' and type='post-translational modification';  ambiguity surrounding unsigned 'transcription/translation'. An advantage of this general approach is that the mechanisms/types provided to users are consistent regardless of the kind of edge created.

**Comment by maxkfranz** [comment]
To summarise: Allow any combination in the UI and model.  But use the existing rule set for conversion to Biopax.  If a combination is "invalid" w.r.t. Biopax and the binary interactions specification, then just use the same rules as for the "other" type.

**Comment by maxkfranz** [comment]
@metincansiper If you run out of things to work on, this could be something to look at.  Basically, it is just removing the restrictions of what interaction types go with different entity combinations in the UI.  The biopax conversion code would also need to be updated:  Any combination that would be considered "invalid" in biopax would use the general top-level interaction rules.  

So the `isAllowedForInteraction()` functions could remain the same.  The biopax conversion code could use those functions instead of the UI.

**Comment by metincansiper** [comment]
See #470
