### ISSUE TITLE
Delete complex immediately after dragging out the second last child node

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#514]
Remove the complex from the document as soon as the second last child node is dragged out of the compound node.  It should behave like the demo with the checkbox `true`:

https://cytoscape.org/cytoscape.js-compound-drag-and-drop/

**Comment by maxkfranz** [comment]
The main thing is that the complex should be immediately visually removed for the user.  That means that we don't necessarily need to remove the compound node right away or remove the complex from the document right away:  We could simply hide the complex node when it has only one child.

**Comment by metincansiper** [comment]
@maxkfranz what may be the best way to hide in this case? I think the options in this section (http://js.cytoscape.org/#style/visibility) will not work because they hide the child (old sibling of the node that is being dragged). 

The only way I can imagine so far is having something like the following:

```
{
      selector: 'node:parent.invisible-parent',
      style: {
        'border-opacity': 0,
        'background-opacity': 0,
        'background-image-opacity': 0,
        'text-opacity': 0
      }
    }
```

For the current state of code only the border opacity actually would make the trick but others maybe needed in case the other parts of code changes later. Is there a better way of doing this? If not would this be enough?

**Comment by maxkfranz** [comment]
Yes, that’s the same approach I would use. The individual values prevent inheritance of hiding.

I don’t think we have an element-level, non-inherited hiding property in cyjs.
