### ISSUE TITLE
Shareable summary

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#542]
## Description

**Q: What is the name of the feature?**

A: Shareable summary

**Q: What does this feature enable the user to do?**

A: Communicate and convey a summary of the pathway knowledge they have deposited that pertains to their research article. 

**Q: What information must the user provide to use the feature?**

A: The data provided to the feature will be drawn from previous effort as part of author curation.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: Intend on accommodating major platform, namely Twitter; Also a web view available on our system.

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: These authors get a way to share their effort on major social media platforms and links to a web view. Enables them to drive awareness of their research.
- Editor: The journal gets deeper engagement with their article content, and shareable summaries can drive readers back to the original article on their web site

### Details

- Caption
- Links (author, journal, paper)
- Citation -- title design | ref. tool | explore from one factoid to another factoid (based on the citation graph)
- Journal branding -- logo, colour scheme, etc. | links
- Tags (keywords, context, topical)

**Comment by maxkfranz** [comment]
The social media side of this issue has been addressed by PR #583.  However, this issue should remain open for further discussion and review of the read-only view.

Some initial concerns:

- Rework of the tooltip/tippy components.  A tippy can flip strangely when its height changes.  On small screens, the a tippy should probably be in a fixed position (probably near the bottom of the screen) so that it always fits properly.
- There are probably random bugs in the read-only view.  Some editing components may be visible, for example.
- The "Share" button should probably be reworked on the read-only view.
- The title, author names, etc. should be links.  This should be a part of the reworking of the document metadata.
