### ISSUE TITLE
Landing page tweaks: copy etc.

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#568]
- [x] Shorten the text descriptions for each section.
- [x] Update the gradient on the top panel.  It should cover more of the image so that that logo is legible (when the window is small).
- [x] Tweak the style to avoid text overflow (on small desktop windows).
- [x] Change the background images s.t. their names are generic.  Avoid words like "banner" or "share", as those file names can be forbidden by adblockers.  For example, Adguard, which is probably the most popular adblocker for Safari, blocks our share image.

**Comment by maxkfranz** [comment]
@gbader @jvwong This is the place to discuss tweaks to the homepage.  You can see a preview of the homepage on the CI server: https://unstable.factoid.baderlab.org

Add your comments here and I'll update the list with the suggested changes.

**Comment by jvwong** [comment]
### Feedback 

- General
  - Check out different form factors - text size and placement on small and large screens
  - Ideally compact each section text
- Section: Summarize
  - Biologists interested in sharing and community rather than ‘cloud-computable’ nature (computational)
  - ‘Easy to use’ superfluous 
- Section: Share
  - Clarify which kind of researchers?
  - 3rd point superfluous. Incorporate ‘share’ and ‘colleagues’ into first sentence
  - Share  - image missing (ad-blocking)
- Section: Discover
  - Simplify; Merge  3rd sentence; grammar - ‘others?’
  - ‘Automatically organises,...makes it searchable on the internet’ etc
  - Community aspect - allow you to find researchers with like interests 
  - Discover - Who’s the person; can we get someone

**Comment by jvwong** [comment]
FYI:
![image](https://user-images.githubusercontent.com/4706307/67801944-a98e7200-fa60-11e9-8639-e872212407ce.png)

**Comment by jvwong** [comment]
We should include a 'worked-example' to concretely illustrate the goal and capabilities of the system. Can consider using one of our author-submitted documents from Molecular Cell pilot.

**Comment by maxkfranz** [comment]
@jvwong 

- Images from the emails (high res)
- Paper titles & metadata -- title & ID for now

**Comment by jvwong** [comment]
paper:
-  [SLC19A1 Is an Importer of the Immunotransmitter cGAMP](https://www.ncbi.nlm.nih.gov/pubmed/31126740)
- id: 7826fd5b-d5af-4f4c-9645-de5264907272

> Images from the emails (high res)

Not sure what you meant here?
