### ISSUE TITLE
Browsing: Beyond the carousel

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#863]
## Description

**Q: What is the name of the feature?**

A: Browse (beyond the carousel)

**Q: What does this feature enable the user to do?**

A: Access any public document via homepage

**Q: What information must the user provide to use the feature?**

A: N/A

**Q: How does this feature affect each class of user (persona)?**

A:  All would benefit from browsing and exploration 

### Mockup

This is a common pattern now.  An popular example is [Pinterest](https://www.pinterest.ca/search/pins/?q=french%20toast&rs=typed) -- an infinite scroll grid and a search bar.

### Details

- Grid UI
  - [react-infinite-scroll](https://www.npmjs.com/package/react-infinite-scroll-component)
  - CSS grid or CSS flex box
- Search has several options for the back end:
  - [Google custom search JSON API](https://developers.google.com/custom-search/v1/introduction)
  - [rethinkdb log stash](logstash-input-rethinkdb)
  - [rethinkdb elastic search sync](https://rethinkdb.com/docs/elasticsearch/)
  - Use elastic search manually
    - Rebuild the index when you start the factoid server
    - Add to index on submit

**Comment by maxkfranz** [comment]
I've fleshed out the issue description more, including links for reference.

**Comment by maxkfranz** [comment]
Note that the ideal version of this would be to delegate to Google rather than to have our own page.  Google search results are much more discoverable because most people start from Google.  Only users who already know about Biofactoid would be able to use a search page that we host  ourselves.

The CTA button here could be replaced with a button that starts a Google search: 

![Screen Shot 2020-10-13 at 10 20 46 AM](https://user-images.githubusercontent.com/989043/95873336-d43f0c80-0d3d-11eb-990d-8ec14af46b9c.png)

A search link could be added to the navigation items at the top of the page (i.e. beside 'contact', 'twitter').  Further, a search button could be added alongside the existing 'add my article' button:

![Screen Shot 2020-10-13 at 10 22 54 AM](https://user-images.githubusercontent.com/989043/95873637-1c5e2f00-0d3e-11eb-899c-9e7a55441283.png)

**Comment by jvwong** [comment]
Yeah I agree. This is related to 'Index images via sitemap' in https://github.com/PathwayCommons/factoid/issues/842#issuecomment-707850543. 

Also we should be mindful of when this sort of thing should be handled by [PC SIFGraph](https://www.pathwaycommons.org/sifgraph/swagger-ui.html)

**Comment by maxkfranz** [comment]
There's also Google Custom Search: https://programmablesearchengine.google.com/about/

That may have more options on how to control how the search results look (i.e. show rich cards).

**Comment by maxkfranz** [comment]
The custom search has a JSON API that could power an eventual grid browser page.

**Comment by jvwong** [comment]
For the sake of time, scope this issue strictly to browsing. Can reuse ideas for "search" later...

 - 1. Homepage: Some way to link to browse all

![Home](https://user-images.githubusercontent.com/4706307/120850055-ed066780-c544-11eb-8d64-8955f39a629c.png)

 - 2. New page: Scroll to browse

![Grid](https://user-images.githubusercontent.com/4706307/120850062-ef68c180-c544-11eb-8772-90f09a084e67.png)

**Comment by jvwong** [comment]
This is related to #909

**Comment by maxkfranz** [comment]
I had something similar in mind:

https://user-images.githubusercontent.com/989043/120855068-fe9f3d80-c54b-11eb-8337-1ac110dddd6b.mov

- The results there are currently canned, because we don't have a search service.
- If the list of all factoids is small and cached, then we can show all the results with scrolling when you hit "Search" instead of showing the results only after you type.
- If the list of all factoids is small, we don't technically need a proper search service -- for now.  We can do an in-memory search on the full list.

**Comment by maxkfranz** [comment]
https://www.npmjs.com/package/minisearch

**Comment by jvwong** [comment]
Oh great that looks exactly the same - didn't want to go to another page anyways.
String-match search in memory is good enough for the time being

**Comment by jvwong** [comment]
Let me know if you have a branch or if you want me to work on anything.

**Comment by maxkfranz** [comment]
It would be really helpful if you could look into the minisearch library and make a class with a search function — search(qString). The class should have an index function that takes in all the doc jsons from our /documents route. 

I still have some kinks to work out in the UI, but I wanted to share the video asap

**Comment by jvwong** [comment]
In doing workup for #1004, I looked at overlapping gene mentions across docs (excluding those by the same author), lots of potentially interesting stuff, just stashing the links here for now

**Comment by jvwong** [comment]
#986 gets you the last 100 public docs.
