### ISSUE TITLE
Caching of recent factoids

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#909]
- The query to load the carousel on the homepage is slow.  It would be better UX to show the result right away.
- The cache should apply only to the new documents list, as shown on the homepage in the carousel (i.e. newest 20).
- Cache the result of  GET [`/api/document`](https://biofactoid.org/api/#/Document/get_api_document) in memory on the server.
- Invalidate the cache on PATCH [`/api/document/{id}/{secret}`](https://biofactoid.org/api/#/Document/patch_api_document__id___secret_), i.e. on submission.
- The cache may contain only the list of document IDs to keep things simple.  This avoids cases where document data changes in the interim, which may be difficult to monitor.  The lookups by ID should be much faster than the existing query with sorting and filtering.
- Queries that specify non-default parameters (e.g. not just the newest 20 docs) bypass caching entirely.  We just need the homepage to be fast.

**Comment by jvwong** [comment]
@maxkfranz @gbader 

I have been testing a staging instance of factoid (beta.biofactoid.org; Digital Ocean) that includes caching for document pathway images on the homepage/search.

I noticed that the initial load of the search results is very memory intensive, to the point where it attempts to use up more memory than is available on the Droplet (maximum 8 GB, also the size of the production Droplet). The result is that the OS kills off other containers, namely the  Elasticsearch container and often the factoid container itself. The image below shows the stats at this point (16:10). Aside: Testing locally and on unstable didn't reveal this as the hosts both had a ton of RAM (>32 GB).

<img width="1002" alt="beta-biofactoid-DO-stats-memory-pre-post-resize" src="https://user-images.githubusercontent.com/4706307/161341130-38e40032-4e21-46a3-b5d4-25052d895690.png">

I tried an experiment where I resized the staging Droplet from 8GB to 16GB of memory, everything else the same (took about 4 min - this is the break point in the chart above). When I relaunched the factoid container and loaded the search, the memory was sufficient (little after 16:50 in the chart) and the factoid container peak usage was around 8 GB RAM.

After caching, the factoid container settles down and uses only around 600 MB of RAM.

So I think we might need to consider upping the production Droplet RAM (16 GB = $80/mo whereas our 8GB = $40/month), otherwise this version of the search won't work well. Alternatives ?  

PS. Initially I  tried varying the env var `DOCUMENT_IMAGE_CACHE_SIZE` but this didn't have any effect.

**Comment by maxkfranz** [comment]
It can't hurt to upgrade the VM.  

Have we limited the amount of memory that each container can use?  Things like the DB shouldn't be allowed to use unbounded amounts of memory.

**Comment by jvwong** [comment]
> Have we limited the amount of memory that each container can use? Things like the DB shouldn't be allowed to use unbounded amounts of memory.

The only docker container limit is on the RethinkDB container (2GB). Otherwise I let them fluctuate, and the only other container that eats memory is Elasticsearch (~3.2GB). 

Aside: [applying memory limits to containers](https://docs.docker.com/compose/compose-file/compose-file-v3/#resources), requires the use of docker stack (not compose), although it still works with compose on our instance for some reason. I probably need to [sort this out](https://vsupalov.com/difference-docker-compose-and-docker-stack/).

**Comment by jvwong** [comment]
One more thing to try: [memory swap](https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details) settings. 

See also [this SO thread on compatibility](https://stackoverflow.com/questions/42345235/how-to-specify-memory-cpu-limit-in-docker-compose-version-3)

Notes: Might also want to run a caching operation in off-times to ready the cache, improve the UX.

**Comment by jvwong** [comment]
DigitalOcean's 1-Click Docker Droplet (s-4vcpu-8gb; Ubuntu 20.04.2 LTS) has no swap configured by default.

```
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       4.5Gi       1.3Gi       1.0Mi       2.0Gi       2.8Gi
Swap:            0B          0B          0B
```

[How To Add Swap Space on Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04)

**Comment by maxkfranz** [comment]
What’s the root cause of the increased memory usage?  The image cache should only be some MB.  Is there an issue in the node server (e.g. memory leak)?  Could the chrome instance be taking up a lot of memory and not releasing it?  Something else?

**Comment by jvwong** [comment]
I thing its chromium - I went down a rabbit hole of trying a bunch of opts but nothing worked.

**Comment by jvwong** [comment]
I configured the host on the Droplet to have some swap enabled, and this made the changes to Docker/Compose unnecessary. I have encoded this configuration in https://github.com/PathwayCommons/factoid-docker-config/issues/54.

On the upside: the containers can now operate without the host having to invoke the OOM killer on any container (see the Droplet stats below where I fill the cache @17:20, 17:35)

<img width="915" alt="Screen Shot 2022-04-18 at 5 42 55 PM" src="https://user-images.githubusercontent.com/4706307/163882479-6029cbb5-12e4-4680-976f-aa857d0f698d.png">

On the downside: The initial load (empty image cache) is slow - in particular the search, which tries to load many images (i.e. up to `DOCUMENT_IMAGE_CACHE_SIZE` which is 500)  and ends up getting back a HTTP 504 for a subset of these images. So the first user with an empty cache has a crummy experience.

So it might make sense to kick off some nightly CRON to re-fill the cache, so user 1 has a nice experience.

**Comment by maxkfranz** [comment]
That’s a good insight.  If it’s chromium, then it could be we’re allowing lots of virtual tabs to be created in chrome to create all those thumbnails in parallel.  Throwing in a queue may help — e.g. https://www.npmjs.com/package/p-queue <https://www.npmjs.com/package/p-queue> or https://www.npmjs.com/package/throttled-queue <https://www.npmjs.com/package/throttled-queue> .  I think we used something similar for the related papers.  If we have access to N cores for chromium, we could use a limit of N for the queue.  That would keep things fast as possible while keeping memory usage down

**Comment by jvwong** [comment]
ok see https://github.com/PathwayCommons/factoid/issues/1069
