### ISSUE TITLE
Document JSON: Extra organism entry

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#920]
The document JSON has extra (string) entries for organism. 

Example: https://biofactoid.org/api/document/5df17c41-acb7-4c42-a37b-fe323688bc64

```
 "organisms": [
    9606,
    10090,
    "9606"
  ],
```

**Comment by maxkfranz** [comment]
Possibilities:

(1) One of the datasources for grounding is using strings instead of integers for the IDs.

(2) There's a mixup inside the factoid code base.

(3) This document spanned different versions of the grounding service.  One version used strings and another used integers.

Another question would be why mouse is in there at all.  The UI shows only human: https://biofactoid.org/document/5df17c41-acb7-4c42-a37b-fe323688bc64

**Comment by jvwong** [comment]
Turns out this mix only applies to the first few docs added, so case (3).
